### ISSUE TITLE
Terminal rendering not working on Mac

### ISSUE THREAD

**Issue by Atcold** [joeyespo/grip#103]
This
```
$ grip -
Hello **world**!
^Z
 * Running on http://localhost:5000/
```
does not work on Mac. When I press `<Ctrl>`-`Z` I get
```
^Z
[1]+  Stopped                 grip -
```
and nothing more. http://localhost:5000/ says "This webpage is not available".

**Comment by ssokolow** [comment]
On Unixy operating systems (basically every desktop OS except Windows), ^Z in a terminal means "send SIGSTOP to the current foreground process".

Judging by that snip, I'm guessing the intent is to generate an EOF signal, which would be ^D.

**Comment by joeyespo** [comment]
@ssokolow Yeah, for whatever reason, ^Z is the EOF signal on Windows. I don't think there's an equivalent to ^D on Windows.

Would changing grip's Readme to use Unix-style ^D (since it covers both Linux and iOS), and mention that you need to use ^Z on Windows help?

Also, @ssokolow, just curious since you seem to know these things pretty well. Is ^C a cross-platform way of sending `KeyboardInterrupt` (SIGINT)?

**Comment by ssokolow** [comment]
@joeyespo 

I actually had to refresh my memory on that one since it's been a while since I touched that particular aspect of writing Windows apps. (Thank you, [modern.ie](http://modern.ie) VirtualBox VMs)

Ctrl+C does generate `KeyboardInterrupt` on both platforms, but it only seems to correspond to `SIGINT` on Linux.

(On Linux, `signal.signal(signal.SIGINT, some_callback)` will fire in response to Ctrl+C but, on Windows, it doesn't.)

**Comment by Atcold** [comment]
Windows... who does use it anymore? LOL
Anyhow, `<Return>` `<Ctrl>`-`D` works, or, `<Ctrl>`-`D`-`D`.
I suggest to edit the doc with either solutions.

**Comment by joeyespo** [comment]
@ssokolow Ah, ok, that makes sense. Thanks!

@Atcold Keep an open mind, you'd be surprised. But yeah, I think that's a good course of action. Thanks for confirming.
