### ISSUE TITLE
Source code is not rendered

### ISSUE THREAD

**Issue by Atcold** [joeyespo/grip#104]
Sometimes I link some small examples to the documentation.
*Github* renders them with the correct syntax highlighting.
*grip* does not. Yes, I understand this incredible and fantastic script is meant to render documentation, but I think it won't be that complicated to add the correct syntax highlighting for source files. (At the moment, the font is also set to a non mono-spaced serif sans.)

**Comment by joeyespo** [comment]
> Yes, I understand this incredible and fantastic script is meant to render documentation

Thanks! This script is indeed meant to render exactly like GitHub, not necessarily for documentation. So if grip isn't rendering something like GitHub is, that's a bug of grip.

Can you paste a snippet of the Markdown that isn't rendering correctly?

**Comment by Atcold** [comment]
It's not *Markdown*, it's whatever language the script is written in.
Perhaps I was not too clear. I'll try to make myself more understandable.

I write tutorials on *GitHub*, and I link to some code files, from within my Markdown.
*GitHub* render them (the source code) with their correct syntax. *Grip* doesn't.
It would be nice (and I guess quite easy) to get *Grip* to render also source files as *GitHub* does.

Was it clearer? :]

**Comment by joeyespo** [comment]
Ohh, yes! Gotcha, thanks for the clarification.

Yeah, sorry, that is outside the scope of grip. It may very well be easy to do, but that doesn't make it the right decision.

It might not even be as easy as you think. You'd have to make grip language-aware so it can decide which renderer to use. If you're not careful, you could easily corner the project into Markdown + "everything else" formats, making it much more difficult to extend later on since you're now "locked in." More importantly, I believe rendering additional formats still falls outside the scope. At least for now. Software bloat can sink projects, so you need to be deliberate about adding features.

As for viewing source code. Do you really need to see it with grip? The mono-spaced typing guarantees that exactly 130 characters will be displayed on GitHub, so you can easily predict how it will render (e.g. using vertical rulers). And long lines aren't wrapped. If this really is important to you, the API might be able to help you out:

```python
import os
from grip import create_app, supported_extensions

grip_app = create_app()
render_markdown = grip_app.view_functions['render']
def render(filename):
    if os.path.splitext(filename)[1] in supported_extensions:
        return render_markdown(filename)
    else:
        return 'TODO: Render with the appropriate syntax highlighting'
grip_app.view_functions['render'] = render
grip_app.run()
```

Does that help?

**Comment by Atcold** [comment]
OK, as I supposed, it's "out-of-scope".
I thought it would be as easy as rendering the ```syntax in a *Markdown* file.

**Comment by joeyespo** [comment]
Sort of.

It will render with syntax, but it still won't look like viewing a code file on GitHub since it'll be wrapped in a gray box and not show line numbers.

You can still accomplish this with the API though if that's what you really want. But again, "ease of development" doesn't imply "belongs in the code."
