### ISSUE TITLE
Open browser instantly after grip is running

### ISSUE THREAD

**Issue by reorx** [joeyespo/grip#109]
Open a new thread to run `webbrowser.open('http://localhost:5000')` after the HTTP server is running, to automate the redundant process of `switch to browser -> open a tab -> insert/paste url -> type enter`.

If this suggestion is accepted, I would be very glad to send a pull request :D

**Comment by ssokolow** [comment]
Keep in mind that `webbrowser.open` is [currently broken for Firefox](http://bugs.python.org/issue23262).

**Comment by srirams6** [comment]
+1

**Comment by kootenpv** [comment]
+1

**Comment by ssokolow** [comment]
Since my last comment, I've tried [restview](https://github.com/mgedmin/restview), which is like grip but for reStructuredText and it does two things which work well with this proposed feature:

1. It uses a random port number unless one is explicitly specified (port 5000 conflicts with the [Pylons](http://www.pylonsproject.org/projects/pylons-framework/about) development server and pylons always gets there first because, to dogfood a certain app, I have it launch on startup.)
2. restview injects some JavaScript into the rendered page so that, when the on-disk file changes restview can automatically trigger a reload in the browser.

**Comment by joeyespo** [comment]
@reorx It might be ok to have this happen on normal execution. Grip is used in scripting too though, so worst case, would it be fine to put this behind a `-b` / `--browser` option?

@ssokolow Any way around that Firefox issue? It seems like that's an external problem that shouldn't stop us from using `webbrowser.open` today, unless there was another "right" way to do this.

@ssokolow  Also,

1. Nice! I like the random port number idea. I just can't think of any downsides other than "it'll clash with another running project every now and then."

2. Perfect. This is what I plan to do for #19 when I finally get around to it. (Especially since the full `livereload` library seems a bit bulky for just that one feature).

**Comment by ssokolow** [comment]
`0.` Since I posted that, Mozilla reverted the change (but left the option undocumented) to give more time for applications to migrate off it. 

However, if you want to be absolutely sure, you could use this code I cooked up to force `xdg-open` to be chosen over the `webbrowser.Mozilla` backend on Linux:

```python
    if os.name == 'posix' and not platform.mac_ver()[0]:
        with open(os.devnull, 'wb') as nul:
            subprocess.Popen(['xdg-open', request_url], stdout=nul, stderr=nul)
    else:
        webbrowser.open(request_url)
```

1. As far as the random port goes, just re-randomize and try again if you collide. That's what I do.

**Comment by joeyespo** [comment]
@reorx Any idea how to listen for the HTTP server to be running with Flask / Werkzeug?

**Comment by joeyespo** [comment]
@ssokolow @srirams6 I do like having a consistent port across runs like other server tools. I did a one-off random pick that should avoid most collisions (since it will no longer be using the very common `5000`), and the rare collisions can set a port manually with `--port` Mind reviewing https://github.com/joeyespo/grip/pull/124 for the change in port?

**Comment by srirams6** [comment]
@joeyespo We execute the `webbrowser.open` in a separate thread and run `sleep(some_seconds)` To make sure that the server is running. The server should start in 1 or 2 seconds. This is not the best way to do this, but I think it would work. Any ideas?

**Comment by joeyespo** [comment]
@srirams6 [This answer](http://stackoverflow.com/questions/2634235/python-webbrowser-openurl) demonstrates how to do it that avoids race conditions. I'm not exactly sure how to do this with Flask / Werkzeug yet.

Any ideas from anyone here?

**Comment by ssokolow** [comment]
Does Flask/Werkzeug support a two-phase connection setup where you could call `listen` , then fire off `webbrowser.open()`, then continue on to actually start `accept`ing connections?

(That'd solve the race condition because the browser would just sit and wait if it started a request before grip started `accept()`ing. No threads needed.)

**Comment by reorx** [comment]
@joeyespo @ssokolow AFAIK, Flask/Werkzeug could not achieve the two-phase setup described above, it's kind of paradox because below the bottom it is `SocketServer.TCPServer` that start a while True loop to check new incoming TCP connection and then `socket.accept` to receive the request, although this **is** done in two phase: 1. listen to the port 2. if new event then accept, but the two phase are coupled together so tight that at least we couldn't step in at the level of Flask/Werkzeug, the `app.run` calls `http_server.serve_forever()` which will block the thread once starting. So (in a single thread) if we can open the url in browser, it means `serve_forever`  hasn't started yet, on the contrary, if `serve_forever` has started, we never get a chance to open browser.

So in my opinion we have to use thread to achieve opening browser in proper time. The code will be most likely the same as [this answer](http://stackoverflow.com/questions/2634235/python-webbrowser-openurl), only different in how we get to know when the server is started. Since in Flask we couldn't decouple the two step of `make_server` and `serve_forever`, the watcher thread can do something like try to connect to the port, if connection could be established, it's time to open the browser.

I'll demonstrate the code in a new PR later in the evening (UTC +8) after off work :)

**Comment by srirams6** [comment]
@joeyespo @reorx 
Please check #122 out. 
I have checked for the server start before opening the browser.

**Comment by reorx** [comment]
@srirams6 yes, it's exactly what I think of it should be, comment was left in that PR :)

**Comment by srirams6** [comment]
Yes. I was doing that in a rush. I'll fix that and push! 
Thanks :)

**Comment by joeyespo** [comment]
Hey all. Finally got around to wrapping everything up and deploying tonight. Thanks for your patience!
