### ISSUE TITLE
Allow generating html/body-less code to embed into existing page

### ISSUE THREAD

**Issue by v01d** [joeyespo/grip#116]
Or, if not possible (I imagine it would be difficult to deal with the head tag), allow for custom header footer for example.

**Comment by zmwangx** [comment]
Why don't you use the countless existing Markdown engines coupled with countless HTTP servers for this but instead insist on grip?

**Comment by v01d** [comment]
I didn't know I was insisting...
Well, to answer your question, since grip displays things exactly as in github. This feature would allow for better integration to an existing website.

**Comment by zmwangx** [comment]
Sorry if I sounded aggressive, I didn't mean to be. Now I see your point — since you mentioned modifying the head tag I thought you wanted to make it look different.

**Comment by cswarth** [comment]
FWIW, I landed here at grip after trying other markdown tools that seemed to do what you are asking for.  

In particular [marked](https://github.com/chjj/marked) is a GFM parser written in javascript.  You can also run `marked` from the command-line if you have node installed.  This produces html without all the elements (header, margins, etc) that makes it actually look like it does on github.  BTW, the predecessor for `marked` is [Docter](https://github.com/alampros/Docter) which is no longer maintained.

**Comment by joeyespo** [comment]
@v01d Could you go into more detail about what you're trying to do?

Grip currently doesn't render the GitHub-looking page without a `<head>`. The reason is because that's where the styles are placed. I like the idea of embedding, but HTML+CSS isn't exactly composable at the moment (please hurry, [Polymer](https://www.polymer-project.org/)!), so we're left with the question of where to put the styles. Since CSS acts globally, and since Grip doesn't control the style assets, they can easily affect the page you're trying to embed the readme into. So I'm not exactly sure this would be useful despite being easy to implement.

On the other hand, if all you're looking for is a tool to render the raw HTML fragment by [GitHub's API](https://developer.github.com/v3/markdown/), you can use the Grip API. Possibly something similar to [the custom styles issue](https://github.com/joeyespo/grip/issues/98#issuecomment-157964212).

**Comment by joeyespo** [comment]
Closing this for now. Feel free to re-open with more details if you feel I didn't answer your question.

**Comment by clawoflight** [comment]
There is the `scoped` attribute for the `style` tag, which allows adding stylesheets for one tag and it's children only.
However, I think that only Firefox supports it.

I am not interested in this feature, just wanted to leave this here in case that someone needs it.
