### ISSUE TITLE
MediaWiki style links are not rendered correctly

### ISSUE THREAD

**Issue by pstavirs** [joeyespo/grip#138]
```
[[ Link Text | WikiPage ]]
```
are supported by GitHub (see https://github.com/pstavirs/ostinato/wiki) but not by grip

**Comment by joeyespo** [comment]
This isn't something the [GitHub Markdown API](https://developer.github.com/v3/markdown/) supports out-of-the-box. Since Grip's primary focus is on Readme's, and there's [an alternative syntax that works in both](https://help.github.com/articles/adding-links-to-wikis/#using-regular-markup-syntax-to-make-links), I'm going to close this as `out-of-scope`.

(Side note: WikiLinks support was [dropped](https://help.github.com/articles/adding-links-to-wikis/#using-a-wiki-markup-syntax-to-make-links) from GitHub Wiki's that use AsciiDoc. I want to avoid a manual translation because like AsciiDoc, the translation may interfere with the underlying thing you're trying to render.)

Thanks for raising the issue, @pstavirs!
