### ISSUE TITLE
Gitter IM support

### ISSUE THREAD

**Issue by mekoda** [joeyespo/grip#155]
Hi,

Do you have any plans to add [Gitter IM](https://gitter.im/) support? Cool enhancement, and can be very handy when discussing issues or PRs; however, it will represent another contact channel to be monitored.

**Comment by joeyespo** [comment]
I can probably be persuaded because I do see the benefit. But until then, no. The addition of a channel feels burdensome, and with life happening outside of open source, I personally like the slower-paced and asynchronous nature of issues. I hope that makes sense.

Thanks for the suggestion, @mekoda.
