### ISSUE TITLE
Template points to octicons CSS that doesn't exist

### ISSUE THREAD

**Issue by rcausey** [joeyespo/grip#181]
The [index.html](https://github.com/joeyespo/grip/blob/master/grip/templates/index.html) template links to //octicons.github.com/components/octicons/octicons/octicons.css, but the actual CSS file is (I think) here: //octicons.github.com/octicons-logos/octicons-logos.css.

**Comment by joeyespo** [comment]
Hmm, the updated link you found only seems to contain the logo icons, not all of them.

I think all of GitHub is transitioning to their SVG-style icons, but the API seems to be lagging behind. Since the Octicons project [doesn't have the website source published](https://github.com/primer/octicons/issues/30), it's difficult to find a hosted location.

Anyone know where to get them now?

If not, we might have to vendor in the [classic Octicons font](https://github.com/primer/octicons/tree/master/build/font) until [the API](https://developer.github.com/v3/markdown/) renders SVG Octicons.

Thanks for bringing this up, @rcausey.

**Comment by joeyespo** [comment]
I ended up downloading and adding [the font icons](https://octicons.github.com/) from [that project](https://github.com/primer/octicons/tree/master/build/font) to the project directly. Since they're not really used by GitHub anymore, there's no reliable place to grab them from.

I imagine the API will eventually render SVGs and we can remove them again.

v4.3.0 contains this fix. Be sure to run `pip install --upgrade grip`. Thanks for opening the issue @rcausey! And for taking a stab at it, @JasonYao!

**Comment by rcausey** [comment]
Great, thanks @joeyespo!
