### ISSUE TITLE
output html file size

### ISSUE THREAD

**Issue by alexkmbk** [joeyespo/grip#205]
After converting this file - https://github.com/alexkmbk/1CI/blob/master/README_RU.md with --export option, I've got 553 KB output html file size.
-why it is so large (the image linked to it just around 20KB)
-Is there a way to decrease the size of output files?

**Comment by joeyespo** [comment]
This is because the downloaded styles (which make the page look like GitHub) are being injected into the exported HTML file.

You can save size by not inlining the styles:

```bash
$ grip --export --no-inline README_RU.md
```

The resulting file is around 45KB.

But now your output won't be styled correctly because Grip isn't there to fulfill those static assets:

```html
<link rel="icon" href="/__/grip/static/favicon.ico" />
  <link rel="stylesheet" href="/__/grip/asset/frameworks-e53fc1ddbde2a9e5645df620f65c80ef723c741b33293b6f22a2b7f2c8145fcf.css" />
  <link rel="stylesheet" href="/__/grip/asset/github-4664ce357daee067bd8ee8e99e0833d04b115022dbf4ca637241c0f7d1f832b7.css" />
  <link rel="stylesheet" href="/__/grip/asset/site-4b977eeae4ecbfd2f7a7ad7788382645b21e771bbf47835e3793edb12292ff2e.css" />
```

One option is to create the `__/grip/asset/` directory alongside your `README_RU.html` output, put the assets that `grip` serves in there (run `grip` on your README, view source, and download the assets from there), and serve that with `python -m SimpleHTTPServer` (or `-m http.server` if you're using Python 3).

Another option is to hot-link direct back to GitHub. Be aware that GitHub changes their assets and filenames every now and then though.

So using `--no-inline` is less portable, since you'll always have to link back to some copy of the assets when you view the rendered output, but can useful if you're exporting many files and reuse the assets. It's also useful if don't need the assets at all.

Hope this helps!

**Comment by alexkmbk** [comment]
Thank you very much! Btw, it looks like the grip utility now is one of the best.

**Comment by joeyespo** [comment]
@alexkmbk Glad that helped. Thanks :smiley:
