### ISSUE TITLE
markdown commenting

### ISSUE THREAD

**Issue by chrisamow** [joeyespo/grip#215]
Grip doesn't seem to observe markdown  commenting (text not to be included in the generated doc)
The most universally accepted does not seem to work 
"[//]: # "
"(empty line)[comment]: # "

I verified the first of those actually does work on github

http://stackoverflow.com/questions/4823468/comments-in-markdown

**Comment by joeyespo** [comment]
It doesn't look like GitHub supports those:

#### Markdown

```
Test comment: [//]: #

[//]: <> (Test comment)
```

#### Rendered

Test comment: [//]: #

[//]: <> (Test comment)

---

I couldn't get the hacks from that link to work for me on a regular GitHub Markdown page either. Since Grip does what GitHub does, [you can ask for the feature in GitHub](https://github.com/isaacs/github/issues) then Grip will adopt it.

On the other hand, it looks like `<!-- testing -->` *does* work with both GitHub and with Grip. Would that help you instead?

#### Markdown

```
Here's a <!-- test comment -->.
```

#### Rendered

Here's a .

**Comment by chrisamow** [comment]
Thanks Joey!

Strange that you couldn't get the first one to work on a github page because that's where i test/verified.  But your solution works perfect so I'm happy!

**Comment by joeyespo** [comment]
Excellent! No prob.

And thanks for the issue. I hadn't thought about comments in Markdown and what that would look like before now. Always good to learn something new 😄
