### ISSUE TITLE
Mismatch with hashes - local and Github

### ISSUE THREAD

**Issue by JasonThomasData** [joeyespo/grip#235]
I've noticed recently that my repos in Github aren't displaying headings as they used to. Their [official docs](https://guides.github.com/features/mastering-markdown/#examples) now say that there should be a space between # and the heading.

####Example1
#### Example2

---

Here's a screenshot of what Grip shows in grip-4.3.2:
![image](https://cloud.githubusercontent.com/assets/9067490/24753822/2f0ae570-1b17-11e7-89f2-05208beebeb1.png)

---

And on Github:
![image](https://cloud.githubusercontent.com/assets/9067490/24753837/422c289e-1b17-11e7-9042-604acbbe455b.png)

I'm going to have a read now and see what I can do.

**Comment by JasonThomasData** [comment]
So here's an update - I've tried sending requests to the Github API via Postman. Requests to the normal /markdown endpoint are fine, but requests to /markdown/raw do return headings for #heading, which Github actually doesn't render. 

Not sure, maybe that's something they should fix? Maybe they don't know?

**Comment by JasonThomasData** [comment]
Sent them a message see what they say I guess.

**Comment by JasonThomasData** [comment]
OK so Github says that's expected behaviour with the raw endpoint. Maybe we should make a way for the user to specify if they want to see raw markdown or GFM markdown?

At terminal:

`grip -raw`

At browser

`http://localhost:6419/raw`

Then we could disable the raw markdown otherwise, since it doesn't help the project's objective of being as close to Github as possible.

**Comment by joeyespo** [comment]
Thanks for all the details here!

I just tried it out and looks like you're right.

```
###Usage
```

renders differently in a README file than in Grip.

Looks like this may be from some of the recent Markdown changes they made. (I'm planning on opening an issue to track all those changes and fix them in one place. Will get to that soon!)

Since you have a conversation going, any chance you could respond and ask whether [their statement](https://developer.github.com/v3/markdown/#render-a-markdown-document-in-raw-mode) that `/raw` "renders it as plain Markdown without a repository context (just like a README.md file is rendered)" is going to remain true, or if they're going to remove that phrasing. Because as of right now, like you point out, `/raw` is rendering *differently* than what appears on GitHub's README.md.

Thanks for digging in and getting the ball rolling on this 😄

**Comment by JasonThomasData** [comment]
If you're going to do that separately, I can close this issue if you like.

Here's the email I sent:
```
Hello,

This concerns the Github API, and in particular the markdown/raw endpoint. I've made an issue on this repo about this. FYI the project uses the Github API to preview Github readme files.

As my comment explains, posts of #heading to the Github API return a heading element, but, without a space on a Github README.md, a #heading will appear as a paragraph.

Wondering if this is a known issue, or an issue at all - is this intended behaviour?

Best regards,
```

And their response:

```
Hi Jason,

Thanks for getting in touch! The GitHub Flavored Markdown Spec was recently updated to use CommonMark spec. You can read more about the what, the why, and the how here:

https://githubengineering.com/a-formal-spec-for-github-markdown/

What you're seeing is expected behavior. I think you may find this section of our documentation of interest: https://github.github.com/gfm/#atx-headings

At least one space is required between the # characters and the heading’s contents, unless the heading is empty.

https://github.github.com/gfm/#example-34

I hope that helps, but let me know if you have any other questions!

All the best,
```

**Comment by JasonThomasData** [comment]
I've sent them an email to clarify that point.

**Comment by JasonThomasData** [comment]
OK, Github eventually acknowledged the issue and made a patch for it. Now the `raw/` endpoint behaves as expected. My previous message about `raw/` behaving as expected was wrong.

**Comment by joeyespo** [comment]
That's great news!

Thanks for following up with them and reporting back here with the results 😃 

I'll mention this in CHANGES.md in the next release.
