### ISSUE TITLE
Funky headings

### ISSUE THREAD

**Issue by meyer** [joeyespo/grip#244]
I think something in Github’s API must have changed very recently. Sometime in the past day or so my headings started to look like this:

![screenshot 2017-09-22 19 45 52](https://user-images.githubusercontent.com/13781/30769504-ab6f2c66-9fce-11e7-87cd-fbdd0a008437.png)

**Comment by reviewher** [comment]
This seems to happen to all of the headings `#` through `######`:

<img width="871" alt="screen shot 2017-09-22 at 22 54 27" src="https://user-images.githubusercontent.com/24845478/30769546-0eebd2ac-9fe9-11e7-90ea-8a71fea8267f.png">

**Comment by joeyespo** [comment]
Yikes! I just saw this too. Thanks for opening the issue, @meyer!

Yeah, looks like an API bug leaked through:

```bash
$ curl https://api.github.com/markdown -d '{ "text": "# testing" }'
<h1>
<a id="user-content-testing" class="anchor" href="#testing" aria-hidden="true"><span>{:"aria-hidden"=&gt;"true", :class=&gt;"octicon octicon-link"}</span></a>testing</h1>
```

I just contacted [GitHub's API support](https://github.com/contact?form%5Bsubject%5D=APIv3) about it.

It's pretty annoying though, so if they don't respond or say they can't fix it quickly, I'll have time tomorrow to release a short-term workaround.

**Comment by joeyespo** [comment]
Alright. I haven't heard anything back yet. (It's the weekend after all.) I do think this is annoying enough to patch in the meantime, so here's a fix #245.

It's quite hacky (if you have a README that contains `<span>{:"aria-hidden"=&gt;"true", :class=&gt;"octicon octicon-link"}</span>`, it'll be outright replaced with `<span class="octicon octicon-link"></span>`), but gets the job done. As such, I made a note to remove this once GitHub addresses it.

Since I've fallen behind, this release also includes [several other fixes](https://github.com/joeyespo/grip/blob/master/CHANGES.md) that were just waiting on me for a summary and PyPI upload.

Thanks for your patience, all 😃

**Comment by reviewher** [comment]
@joeyespo thanks a lot for your great effort! can confirm that grip 4.4.0 does not show the "funky headings"

**Comment by foxdonut** [comment]
@joeyespo you are a star! 🌟 thank you for fixing this so quickly, much appreciated!

**Comment by joeyespo** [comment]
#### Update

GitHub responded with this:

> Just wanted to let you know that the team deployed some changes which should have fixed this problem. If you can still reproduce this — please let us know.

This was sent last Monday (Sept 25), and I can confirm that it works now. (Thanks for the quick official fix, GitHub!) I'll remove the workaround in the next release 🎉

**Comment by meyer** [comment]
@joeyespo rad, thanks! 💃 💃 💃
