### ISSUE TITLE
image not showing when running export

### ISSUE THREAD

**Issue by robertmarkbram** [joeyespo/grip#295]
I have the following md file where the image displays correctly (using VS Code). I am on a Windows machine and using an absolute path to the image.

```markdown
Text

![](C:/Users/robert.bram/Temp/IntellijDebugConfiguration.png)

Text
```

I then run the following command: `grip temp.md --export temp.html`

```html
<p>Text</p>
<p><a href="" target="_blank" rel="noopener noreferrer"><img alt="" style="max-width:100%;"></a></p>
<p>Text</p>
```

What am I missing here?

Rob
:)

**Comment by Bwvolleyball** [comment]
@robertmarkbram - I believe you need to make the path relative.  The idea behind this project is to try to replicate what a markdown document would look like if it were pushed to GitHub.  This means 2 things:

1) It is assumed that the image lives within the same repo as the markdown document
2) the path to said document is relative.

That being said, if your markdown document lived in the `robert.bram` folder, your path in order to display the png should just be `./Temp/IntellijDebugConfiguration.png`

Hope this helps!

**Comment by joeyespo** [comment]
Hey @robertmarkbram! Thanks for the issue. @Bwvolleyball is correct. You'll need to use relative paths.

If you think about it, it makes sense. GitHub can't serve images from machine-dependent absolute paths, so you probably shouldn't do this. (Look up the `file://` scheme if you absolutely *need* it, but I'd still recommend against this workaround.)
