### ISSUE TITLE
Support custom or no css when using export

### ISSUE THREAD

**Issue by nickjbyrne** [joeyespo/grip#93]
I would like to use the export facility without the included default css, which would enable me to apply differing styles at a later time when i use weasyprint to export to pdf.

**Comment by joeyespo** [comment]
You can currently use the `STYLE_URLS` setting for adding additional styles.

Just to be clear, you're suggesting that you'd rather apply styles from a blank slate, rather than add styles on top of GitHub's to make exporting easier, right?

**Comment by joeyespo** [comment]
Thinking more about this, you can actually do this today without a new CLI argument.

Because you're already trying to automate something using the exporter, you can use [grip's API](https://github.com/joeyespo/grip#api) to for further tweak it to your needs.

For example:

```python
import grip
grip.export(render_inline=False)
```

This will generate a `README.html` file without any styles inlined into the document. [Here's an example](https://gist.github.com/joeyespo/519070535829e81b513e) of running this on grip's README. Notice that the assets are still there, but they're pointing to `/grip-cache`. This will likely not exist since the grip server won't be running when you're generating a PDF. So you can probably just ignore them (or run code that deletes them if you like). From there, you can add or inject your own styles right after the `<style>` line.

This seems more appropriate than introducing another CLI argument for a special case. If this is still too complicated, it might be worth adding another argument to `export`, but probably not to the CLI.

**Comment by joeyespo** [comment]
Opened a new issue for extending `export` at #98.

**Comment by joeyespo** [comment]
@nickjbyrne This is [now possible](https://github.com/joeyespo/grip/issues/98#issuecomment-157964212) using the API.

Does that help?
