### ISSUE TITLE
Links to header anchor does not work

### ISSUE THREAD

**Issue by veelenga** [joeyespo/grip#94]
Default markdown syntax not working with grip:

````
[LinkName](#Header1)
...

## Header1
````

Real example you can find  in [prelude](https://github.com/bbatsov/prelude) repo (table of contents section).

**Comment by joeyespo** [comment]
You're right! There's [code](https://github.com/joeyespo/grip/blob/351e32501d0a84c4841ef7b0eaf50e799f161bfe/grip/templates/index.html#L46-L59) that specifically handles this case. Looks like GitHub now uses HTML `id` instead of `name` to mark their README anchors.

Should be an easy fix:

```js
function scrollToHash() {
      if (location.hash && !document.querySelector(":target")) {
        var element = document.getElementById('user-content-' + location.hash.slice(1));
        if (element) {
          element.scrollIntoView();
        }
      }
    }
```

If you need this immediately, feel free to patch your local clone. I'll deploy a new version with this fix as soon as I have some time.

**Comment by veelenga** [comment]
Thanks for quick response.
Sure, it's not a problem. I'm going to fix it and pull.

**Comment by joeyespo** [comment]
Just released a new version with a fix to this. Be sure to `pip install --upgrade grip`.

**Comment by veelenga** [comment]
Thanks!
